### ISSUE TITLE
IME video

### ISSUE THREAD

**Issue by johanmalm** [johanmalm/labwc-0.7.2-release-video#2]
@tokyo4j

Any chance you could do a video line this one https://github.com/johanmalm/labwc-0.8.0-release-video/blob/master/video/300-input-method.gif but in mkv/mp4/similar for the release video?

**Comment by tokyo4j** [comment]
Feel free to ask for changes.

https://github.com/johanmalm/labwc-0.8.0-release-video/assets/22029524/30f4f56c-2fd3-4657-b06d-35060923ecfa

**Comment by johanmalm** [comment]
Thanks. That's great. 
Have added.
What does it say?

**Comment by tokyo4j** [comment]
It says "hello" in Japanese and in Chinese.
